

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class ACRESERVA
{

    public int ACT_ID { get; set; }

    public string USERNAME { get; set; }

    public System.DateTime FECHA { get; set; }

}


public partial class ACTA
{

    public int Act_id { get; set; }

    public string Act_UsuarioGenera { get; set; }

    public Nullable<System.DateTime> Act_FechaGenera { get; set; }

    public string Act_Nombre { get; set; }

    public string Act_Direccion { get; set; }

    public string Act_ubicacion { get; set; }

    public Nullable<int> Act_CustodioId { get; set; }

}


public partial class ACTIVO
{

    public ACTIVO()
    {

        this.CARACTERISTICA = new HashSet<CARACTERISTICA>();

        this.DEPRECIACION = new HashSet<DEPRECIACION>();

        this.DEPRECIACIONSRI = new HashSet<DEPRECIACIONSRI>();

        this.MOVIMIENTO_RFID = new HashSet<MOVIMIENTO_RFID>();

        this.MANTENIMIENTO = new HashSet<MANTENIMIENTO>();

    }


    public int ACT_ID { get; set; }

    public string EMP_ID { get; set; }

    public System.DateTime ACT_FECHACREACION { get; set; }

    public Nullable<System.DateTime> ACT_FECHAINIDEPRE { get; set; }

    public Nullable<bool> ACT_DEPRECIABLESRI { get; set; }

    public Nullable<bool> ACT_DEPRECIABLE { get; set; }

    public Nullable<bool> ACT_DEPRECIADOSRI { get; set; }

    public Nullable<bool> ACT_DEPRECIADONIIF { get; set; }

    public Nullable<System.DateTime> ACT_FECHAINIOPER { get; set; }

    public Nullable<System.DateTime> ACT_FECHAINIDEPRENIIF { get; set; }

    public Nullable<System.DateTime> ACT_FECHABAJA { get; set; }

    public string USERNAME { get; set; }

    public string ACT_TIPO { get; set; }

    public string ACT_CODBARRAS { get; set; }

    public string ACT_CODBARRASPADRE { get; set; }

    public string ACT_CODIGO1 { get; set; }

    public int GRU_ID1 { get; set; }

    public int GRU_ID2 { get; set; }

    public int GRU_ID3 { get; set; }

    public string ACT_FOTO1 { get; set; }

    public string ACT_FOTO2 { get; set; }

    public string ACT_DOC1 { get; set; }

    public string ACT_DOC2 { get; set; }

    public int UGE_ID1 { get; set; }

    public int UGE_ID2 { get; set; }

    public int UGE_ID3 { get; set; }

    public int UGE_ID4 { get; set; }

    public int UOR_ID1 { get; set; }

    public int UOR_ID2 { get; set; }

    public int UOR_ID3 { get; set; }

    public int CUS_ID1 { get; set; }

    public Nullable<int> CUS_ID2 { get; set; }

    public int EST_ID1 { get; set; }

    public Nullable<int> EST_ID2 { get; set; }

    public Nullable<int> EST_ID3 { get; set; }

    public int MAR_ID { get; set; }

    public int MOD_ID { get; set; }

    public string ACT_SERIE1 { get; set; }

    public Nullable<int> COL_ID { get; set; }

    public Nullable<int> ECO_ID1 { get; set; }

    public Nullable<int> ECO_ID2 { get; set; }

    public Nullable<int> PRO_ID { get; set; }

    public string ACT_TIPOING { get; set; }

    public Nullable<decimal> ACT_NUMFACT { get; set; }

    public Nullable<System.DateTime> ACT_FECHACOMPRA { get; set; }

    public Nullable<decimal> ACT_VALORCOMPRA { get; set; }

    public Nullable<int> ACT_ANIO { get; set; }

    public Nullable<int> ACT_VIDAUTIL { get; set; }

    public Nullable<int> ACT_VIDAUTILNIIF { get; set; }

    public Nullable<decimal> ACT_VALORRESIDUALNIIF { get; set; }

    public Nullable<bool> ACT_GARANTIA { get; set; }

    public Nullable<System.DateTime> ACT_FECHAGARANTIAVENCE { get; set; }

    public string ACT_OBSERVACIONES { get; set; }

    public bool ACT_TRANSFEROK { get; set; }

    public Nullable<int> ACT_PPC { get; set; }

    public string ACT_H1 { get; set; }

    public string ACT_H2 { get; set; }

    public string ACT_PE { get; set; }

    public string ACT_OBSERVACIONES2 { get; set; }

    public Nullable<int> ACT_TIPOBAJA { get; set; }

    public string ACT_OBSBAJA { get; set; }

    public Nullable<bool> ACT_BAJAPROCESADA { get; set; }

    public Nullable<bool> ACT_BAJAPROCESADASRI { get; set; }

    public string ACT_RESUMEN { get; set; }

    public Nullable<decimal> ACT_VALORREPO { get; set; }

    public Nullable<decimal> ACT_VALORRAZONABLE { get; set; }

    public Nullable<System.DateTime> ACT_FECHAINVENTARIO { get; set; }

    public string ACT_CODRFID { get; set; }

    public string ACT_STRADICIONAL3 { get; set; }

    public string ACT_RETIQUETAR { get; set; }

    public Nullable<int> ACT_AUTRFID { get; set; }

    public Nullable<int> ACT_FILRFID { get; set; }

    public Nullable<int> ACT_TIPRFID { get; set; }

    public string ACT_SEGURO { get; set; }

    public Nullable<int> ACT_TIPOSEGURO { get; set; }

    public string ACT_ESTADOMANT { get; set; }

    public Nullable<System.DateTime> ACT_FECHAENVIOMANT { get; set; }

    public Nullable<System.DateTime> ACT_FECHAREGRESOMANT { get; set; }

    public string ACT_DESCRIPCIONLARGA { get; set; }

    public string ACT_NUMPOLIZA { get; set; }

    public Nullable<int> ACT_VIGENCIAPOLIZAMESES { get; set; }

    public Nullable<System.DateTime> ACT_FECHAEMISIONPOLIZA { get; set; }

    public Nullable<System.DateTime> ACT_FECHAVENCEPOLIZA { get; set; }

    public Nullable<decimal> ACT_VALORASEGURADO { get; set; }

    public Nullable<decimal> ACT_DEPREACUMULADA { get; set; }



    public virtual COLOR COLOR { get; set; }

    public virtual CUSTODIO CUSTODIO { get; set; }

    public virtual ESTRUCOMP ESTRUCOMP { get; set; }

    public virtual ESTRUCOMP ESTRUCOMP1 { get; set; }

    public virtual EMPRESA EMPRESA { get; set; }

    public virtual ESTADO ESTADO { get; set; }

    public virtual ESTADO ESTADO1 { get; set; }

    public virtual GRUPO GRUPO { get; set; }

    public virtual GRUPO GRUPO1 { get; set; }

    public virtual GRUPO GRUPO2 { get; set; }

    public virtual MARCA MARCA { get; set; }

    public virtual MODELO MODELO { get; set; }

    public virtual PROVEEDOR PROVEEDOR { get; set; }

    public virtual UGEOGRAFICA UGEOGRAFICA { get; set; }

    public virtual UGEOGRAFICA UGEOGRAFICA1 { get; set; }

    public virtual UGEOGRAFICA UGEOGRAFICA2 { get; set; }

    public virtual UGEOGRAFICA UGEOGRAFICA3 { get; set; }

    public virtual UORGANICA UORGANICA { get; set; }

    public virtual UORGANICA UORGANICA1 { get; set; }

    public virtual ICollection<CARACTERISTICA> CARACTERISTICA { get; set; }

    public virtual ICollection<DEPRECIACION> DEPRECIACION { get; set; }

    public virtual ICollection<DEPRECIACIONSRI> DEPRECIACIONSRI { get; set; }

    public virtual ICollection<MOVIMIENTO_RFID> MOVIMIENTO_RFID { get; set; }

    public virtual TIPO_SEGURO TIPO_SEGURO { get; set; }

    public virtual ICollection<MANTENIMIENTO> MANTENIMIENTO { get; set; }

}


public partial class ANIO
{

    public int ANI_ID { get; set; }

}


public partial class aspnet_Applications
{

    public aspnet_Applications()
    {

        this.aspnet_Membership = new HashSet<aspnet_Membership>();

        this.aspnet_Paths = new HashSet<aspnet_Paths>();

        this.aspnet_Roles = new HashSet<aspnet_Roles>();

        this.aspnet_Users = new HashSet<aspnet_Users>();

    }


    public string ApplicationName { get; set; }

    public string LoweredApplicationName { get; set; }

    public System.Guid ApplicationId { get; set; }

    public string Description { get; set; }



    public virtual ICollection<aspnet_Membership> aspnet_Membership { get; set; }

    public virtual ICollection<aspnet_Paths> aspnet_Paths { get; set; }

    public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }

    public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }

}


public partial class aspnet_Membership
{

    public System.Guid ApplicationId { get; set; }

    public System.Guid UserId { get; set; }

    public string Password { get; set; }

    public int PasswordFormat { get; set; }

    public string PasswordSalt { get; set; }

    public string MobilePIN { get; set; }

    public string Email { get; set; }

    public string LoweredEmail { get; set; }

    public string PasswordQuestion { get; set; }

    public string PasswordAnswer { get; set; }

    public bool IsApproved { get; set; }

    public bool IsLockedOut { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime LastLoginDate { get; set; }

    public System.DateTime LastPasswordChangedDate { get; set; }

    public System.DateTime LastLockoutDate { get; set; }

    public int FailedPasswordAttemptCount { get; set; }

    public System.DateTime FailedPasswordAttemptWindowStart { get; set; }

    public int FailedPasswordAnswerAttemptCount { get; set; }

    public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }

    public string Comment { get; set; }



    public virtual aspnet_Applications aspnet_Applications { get; set; }

    public virtual aspnet_Users aspnet_Users { get; set; }

}


public partial class aspnet_Paths
{

    public aspnet_Paths()
    {

        this.aspnet_PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();

    }


    public System.Guid ApplicationId { get; set; }

    public System.Guid PathId { get; set; }

    public string Path { get; set; }

    public string LoweredPath { get; set; }



    public virtual aspnet_Applications aspnet_Applications { get; set; }

    public virtual aspnet_PersonalizationAllUsers aspnet_PersonalizationAllUsers { get; set; }

    public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }

}


public partial class aspnet_PersonalizationAllUsers
{

    public System.Guid PathId { get; set; }

    public byte[] PageSettings { get; set; }

    public System.DateTime LastUpdatedDate { get; set; }



    public virtual aspnet_Paths aspnet_Paths { get; set; }

}


public partial class aspnet_PersonalizationPerUser
{

    public System.Guid Id { get; set; }

    public Nullable<System.Guid> PathId { get; set; }

    public Nullable<System.Guid> UserId { get; set; }

    public byte[] PageSettings { get; set; }

    public System.DateTime LastUpdatedDate { get; set; }



    public virtual aspnet_Paths aspnet_Paths { get; set; }

    public virtual aspnet_Users aspnet_Users { get; set; }

}


public partial class aspnet_Profile
{

    public System.Guid UserId { get; set; }

    public string PropertyNames { get; set; }

    public string PropertyValuesString { get; set; }

    public byte[] PropertyValuesBinary { get; set; }

    public System.DateTime LastUpdatedDate { get; set; }



    public virtual aspnet_Users aspnet_Users { get; set; }

}


public partial class aspnet_Roles
{

    public aspnet_Roles()
    {

        this.aspnet_Users = new HashSet<aspnet_Users>();

    }


    public System.Guid ApplicationId { get; set; }

    public System.Guid RoleId { get; set; }

    public string RoleName { get; set; }

    public string LoweredRoleName { get; set; }

    public string Description { get; set; }



    public virtual aspnet_Applications aspnet_Applications { get; set; }

    public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }

}


public partial class aspnet_SchemaVersions
{

    public string Feature { get; set; }

    public string CompatibleSchemaVersion { get; set; }

    public bool IsCurrentVersion { get; set; }

}


public partial class aspnet_Users
{

    public aspnet_Users()
    {

        this.aspnet_PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();

        this.aspnet_Roles = new HashSet<aspnet_Roles>();

    }


    public System.Guid ApplicationId { get; set; }

    public System.Guid UserId { get; set; }

    public string UserName { get; set; }

    public string LoweredUserName { get; set; }

    public string MobileAlias { get; set; }

    public bool IsAnonymous { get; set; }

    public System.DateTime LastActivityDate { get; set; }



    public virtual aspnet_Applications aspnet_Applications { get; set; }

    public virtual aspnet_Membership aspnet_Membership { get; set; }

    public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }

    public virtual aspnet_Profile aspnet_Profile { get; set; }

    public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }

}


public partial class aspnet_WebEvent_Events
{

    public string EventId { get; set; }

    public System.DateTime EventTimeUtc { get; set; }

    public System.DateTime EventTime { get; set; }

    public string EventType { get; set; }

    public decimal EventSequence { get; set; }

    public decimal EventOccurrence { get; set; }

    public int EventCode { get; set; }

    public int EventDetailCode { get; set; }

    public string Message { get; set; }

    public string ApplicationPath { get; set; }

    public string ApplicationVirtualPath { get; set; }

    public string MachineName { get; set; }

    public string RequestUrl { get; set; }

    public string ExceptionType { get; set; }

    public string Details { get; set; }

}


public partial class BLOQUEO_PASSWORD
{

    public int Id { get; set; }

    public string usuario { get; set; }

    public string hora_bloqueo { get; set; }

    public string hora_desbloqueo { get; set; }

    public int tipo_bloqueo { get; set; }

}


public partial class Cabecera
{

    public int id { get; set; }

    public int IdCabeceraModulo { get; set; }

    public System.DateTime FechaContable { get; set; }

    public short SucursalOrigen { get; set; }

    public decimal TotalDebitoMn { get; set; }

    public decimal TotalDebitoMe { get; set; }

    public decimal TotalCreditoMn { get; set; }

    public decimal TotalCreditoMe { get; set; }

    public short Registros { get; set; }

    public string Digitador { get; set; }

    public string Autorizador { get; set; }

    public string EstadoProceso { get; set; }

    public int LocalidadOrigen { get; set; }

    public int ResponsableOrigen { get; set; }

    public Nullable<int> ModuloCobis { get; set; }

}


public partial class CARACTERISTICA
{

    public int CAR_ID { get; set; }

    public int ACT_ID { get; set; }

    public int CFA_ID { get; set; }

    public string CAR_VALOR { get; set; }

    public Nullable<int> UNI_ID { get; set; }

    public string CAR_DEL { get; set; }



    public virtual ACTIVO ACTIVO { get; set; }

    public virtual CFAMILIA CFAMILIA { get; set; }

    public virtual UNIDAD UNIDAD { get; set; }

}


public partial class CARGO
{

    public CARGO()
    {

        this.CUSTODIO = new HashSet<CUSTODIO>();

    }


    public int CGO_ID { get; set; }

    public string CGO_NOMBRE { get; set; }



    public virtual ICollection<CUSTODIO> CUSTODIO { get; set; }

}


public partial class CCAR
{

    public int CCA_ID { get; set; }

    public string CCA_NOMBRE { get; set; }

}


public partial class CFAMILIA
{

    public CFAMILIA()
    {

        this.CARACTERISTICA = new HashSet<CARACTERISTICA>();

    }


    public int CFA_ID { get; set; }

    public int GRU_ID { get; set; }

    public string CFA_NOMBRE { get; set; }

    public int CFA_ORDEN { get; set; }

    public bool CFA_UNIDADES { get; set; }

    public string CFA_OBLIGATORIO { get; set; }



    public virtual ICollection<CARACTERISTICA> CARACTERISTICA { get; set; }

    public virtual GRUPO GRUPO { get; set; }

}


public partial class CODIGO
{

    public string EMP_ID { get; set; }

    public string COD_PREFIJO { get; set; }

    public string COD_SUFIJO { get; set; }

    public int COD_SECUENCIAL { get; set; }

    public int COD_VERIFICADOR { get; set; }

}


public partial class CODIGOMASIVO
{

    public string EMP_ID { get; set; }

    public string COD_PREFIJO { get; set; }

    public string COD_SUFIJO { get; set; }

    public int COD_SECUENCIAL { get; set; }

    public int COD_VERIFICADOR { get; set; }

}


public partial class COLOR
{

    public COLOR()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

    }


    public int COL_ID { get; set; }

    public string COL_NOMBRE { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

}


public partial class CUSTODIO
{

    public CUSTODIO()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

        this.XCUOR = new HashSet<XCUOR>();

    }


    public int CUS_ID { get; set; }

    public string CUS_CODIGO { get; set; }

    public string CUS_APELLIDOS { get; set; }

    public string CUS_NOMBRES { get; set; }

    public string CUS_CEDULA { get; set; }

    public string CUS_TELEFONOFIJO { get; set; }

    public string CUS_EXT { get; set; }

    public string CUS_CELULAR { get; set; }

    public string CUS_FOTO { get; set; }

    public string CUS_EMAIL { get; set; }

    public Nullable<int> CGO_ID { get; set; }

    public string CUS_ESTADO { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

    public virtual CARGO CARGO { get; set; }

    public virtual ICollection<XCUOR> XCUOR { get; set; }

}


public partial class DEPRECIACION
{

    public int DEP_ID { get; set; }

    public int DEP_VIDAUTIL { get; set; }

    public decimal DEP_VALORRESIDUAL { get; set; }

    public decimal DEP_SALDOXDEPRE { get; set; }

    public decimal DEP_DEPREACUM { get; set; }

    public int DEP_PERTRANS { get; set; }

    public int DEP_PERREMA { get; set; }

    public decimal DEP_DEPREPERIODO { get; set; }

    public Nullable<System.DateTime> DEP_FECHAPROX { get; set; }

    public string DEP_TIPO { get; set; }

    public int ACT_ID { get; set; }

    public string DEP_CCOSTO { get; set; }

    public string DEP_GRUPO { get; set; }

    public string DEP_OBS { get; set; }

    public Nullable<bool> DEP_BAJA { get; set; }



    public virtual ACTIVO ACTIVO { get; set; }

}


public partial class DEPRECIACIONSRI
{

    public int DEP_ID { get; set; }

    public int DEP_VIDAUTIL { get; set; }

    public decimal DEP_VALORRESIDUAL { get; set; }

    public decimal DEP_SALDOXDEPRE { get; set; }

    public decimal DEP_DEPREACUM { get; set; }

    public int DEP_PERTRANS { get; set; }

    public int DEP_PERREMA { get; set; }

    public decimal DEP_DEPREPERIODO { get; set; }

    public Nullable<System.DateTime> DEP_FECHAPROX { get; set; }

    public string DEP_TIPO { get; set; }

    public int ACT_ID { get; set; }

    public string DEP_CCOSTO { get; set; }

    public string DEP_GRUPO { get; set; }

    public string DEP_OBS { get; set; }

    public Nullable<bool> DEP_BAJA { get; set; }

    public Nullable<System.DateTime> DEP_FECHABAJA { get; set; }



    public virtual ACTIVO ACTIVO { get; set; }

}


public partial class DetalleModulo
{

    public int id { get; set; }

    public int IdCabeceraModulo { get; set; }

    public int Registro { get; set; }

    public string Cuenta { get; set; }

    public byte IdMoneda { get; set; }

    public short SucursalDestino { get; set; }

    public string Detalle { get; set; }

    public decimal DebitoMn { get; set; }

    public decimal DebitoMe { get; set; }

    public decimal CreditoMn { get; set; }

    public decimal CreditoMe { get; set; }

    public string TipoTransaccion { get; set; }

    public string TipoNegociacion { get; set; }

    public string Operacion { get; set; }

    public string Referencia { get; set; }

    public int LocalidadDestino { get; set; }

    public int ResponsableDestino { get; set; }

}


public partial class DGENERADA
{

    public int DGE_ID { get; set; }

    public System.DateTime DGE_GENERADA { get; set; }

    public System.DateTime DGE_SIGUIENTE { get; set; }

    public string DGE_TIPO { get; set; }

    public string DGE_USUARIO { get; set; }

}


public partial class DGENERADASRI
{

    public int DGE_ID { get; set; }

    public System.DateTime DGE_GENERADA { get; set; }

    public System.DateTime DGE_SIGUIENTE { get; set; }

    public string DGE_TIPO { get; set; }

    public string DGE_USUARIO { get; set; }

}


public partial class EMPRESA
{

    public EMPRESA()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

    }


    public string EMP_ID { get; set; }

    public string EMP_NOMBRE { get; set; }

    public string EMP_PREFIJO { get; set; }

    public int EMP_TOTALDIGITOS { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

}


public partial class ESTADO
{

    public ESTADO()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

        this.ACTIVO1 = new HashSet<ACTIVO>();

    }


    public int EST_ID { get; set; }

    public string EST_NOMBRE { get; set; }

    public string EST_GRUPO { get; set; }

    public int EST_ORDEN { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

    public virtual ICollection<ACTIVO> ACTIVO1 { get; set; }

}


public partial class ESTRUCOMP
{

    public ESTRUCOMP()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

        this.ACTIVO1 = new HashSet<ACTIVO>();

    }


    public int ECO_ID { get; set; }

    public string ECO_NOMBRE { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

    public virtual ICollection<ACTIVO> ACTIVO1 { get; set; }

}


public partial class GRUPO
{

    public GRUPO()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

        this.ACTIVO1 = new HashSet<ACTIVO>();

        this.ACTIVO2 = new HashSet<ACTIVO>();

        this.CFAMILIA = new HashSet<CFAMILIA>();

        this.PROVEEDOR = new HashSet<PROVEEDOR>();

    }


    public int GRU_ID { get; set; }

    public string GRU_NOMBRE { get; set; }

    public int GRU_PADRE { get; set; }

    public int GRU_NIVEL { get; set; }

    public string GRU_CODIGO { get; set; }

    public string GRU_CTA1 { get; set; }

    public string GRU_CTA2 { get; set; }

    public string GRU_CTA3 { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

    public virtual ICollection<ACTIVO> ACTIVO1 { get; set; }

    public virtual ICollection<ACTIVO> ACTIVO2 { get; set; }

    public virtual ICollection<CFAMILIA> CFAMILIA { get; set; }

    public virtual GRUPOSRI GRUPOSRI { get; set; }

    public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }

}


public partial class GRUPOSRI
{

    public int GRU_ID { get; set; }

    public int GRU_VUSRI { get; set; }



    public virtual GRUPO GRUPO { get; set; }

}


public partial class HCODIGO
{

    public int HCO_ID { get; set; }

    public System.DateTime HCO_FECHA { get; set; }

    public string HCO_USUARIO { get; set; }

    public string HCO_TIPO { get; set; }

    public string HCO_COD1 { get; set; }

    public string HCO_COD2 { get; set; }

    public int HCO_NUMERO { get; set; }

}


public partial class HFOTO
{

    public int HFO_ID { get; set; }

    public System.DateTime HFO_FECHA { get; set; }

    public string USERNAME { get; set; }

    public int ACT_ID { get; set; }

    public string HFO_FOTO1 { get; set; }

    public string HFO_FOTO2 { get; set; }

    public string CUS_ID1 { get; set; }

    public string CUS_ID2 { get; set; }

    public string HFO_FOTO3 { get; set; }

}


public partial class HISTORIAL_PASSWORD
{

    public int Id { get; set; }

    public string usuario { get; set; }

    public string password { get; set; }

    public System.DateTime fechacreacion { get; set; }

    public int cont { get; set; }

}


public partial class HUCUSTODIO
{

    public int HUC_ID { get; set; }

    public string USERNAME { get; set; }

    public System.DateTime HUC_FECHA { get; set; }

    public int ACT_ID { get; set; }

    public string UGE_ID1 { get; set; }

    public string UGE_ID2 { get; set; }

    public string UGE_ID3 { get; set; }

    public string UGE_ID4 { get; set; }

    public string UOR_ID1 { get; set; }

    public string UOR_ID2 { get; set; }

    public string UOR_ID3 { get; set; }

    public string CUS_ID1 { get; set; }

    public string CUS_ID2 { get; set; }

    public string EST_ID1 { get; set; }

    public string EST_ID2 { get; set; }

    public string EST_ID3 { get; set; }

    public string EST_MANT { get; set; }

}


public partial class INVALIDCREDENTIALSLOG
{

    public int InvalidCredentialsLogID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public Nullable<bool> IsApproved { get; set; }

    public Nullable<bool> IsLockedOut { get; set; }

    public string IPAddress { get; set; }

    public System.DateTime LoginAttemptDate { get; set; }

}


public partial class MACTIVO
{

    public int MAC_ID { get; set; }

    public System.DateTime MAC_FECHA { get; set; }

    public int ACT_ID { get; set; }

    public string USERNAME { get; set; }

    public string MAC_ACCION { get; set; }

}


public partial class MANTENIMIENTO
{

    public int MAN_ID { get; set; }

    public string MAN_DESCRIPCION { get; set; }

    public Nullable<int> TIP_ID_CORRECTIVO { get; set; }

    public Nullable<int> TIP_ID_PREVENTIVO { get; set; }

    public string USERNAME { get; set; }

    public Nullable<System.DateTime> MAN_FECHA { get; set; }

    public int ACT_ID { get; set; }

    public Nullable<bool> MAN_REALIZADO { get; set; }

    public Nullable<System.DateTime> MAN_FECHAPROXINI { get; set; }

    public Nullable<decimal> MAN_VALOR { get; set; }

    public string MAN_NUMDOC { get; set; }

    public string MAN_FORMA { get; set; }

    public Nullable<int> MAN_COBERTURA { get; set; }

    public string MAN_MODALIDAD { get; set; }

    public string MAN_PORMESES { get; set; }

    public string MAN_ESTADO { get; set; }

    public Nullable<System.DateTime> MAN_FECHAPROXFIN { get; set; }

    public Nullable<System.DateTime> MAN_FECHAREALMANT { get; set; }

    public Nullable<System.DateTime> MAN_ENVIOMANT { get; set; }

    public Nullable<System.DateTime> MAN_RETORNOMANT { get; set; }



    public virtual ACTIVO ACTIVO { get; set; }

}


public partial class MARCA
{

    public MARCA()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

        this.MODELO = new HashSet<MODELO>();

    }


    public int MAR_ID { get; set; }

    public string MAR_NOMBRE { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

    public virtual ICollection<MODELO> MODELO { get; set; }

}


public partial class MODELO
{

    public MODELO()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

    }


    public int MOD_ID { get; set; }

    public string MOD_NOMBRE { get; set; }

    public int MAR_ID { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

    public virtual MARCA MARCA { get; set; }

}


public partial class MOVIMIENTO_RFID
{

    public int cod_itemxmov { get; set; }

    public int act_id { get; set; }

    public string mov_codbarras { get; set; }

    public string mov_codLogicard { get; set; }

    public int mov_cusid { get; set; }

    public System.DateTime mov_fecha { get; set; }

    public string mov_hora { get; set; }

    public string mov_ip { get; set; }

    public string mov_portal { get; set; }

    public string mov_estado { get; set; }

    public Nullable<int> mov_antenna { get; set; }

    public Nullable<decimal> mov_NumAdicional1 { get; set; }

    public Nullable<decimal> mov_NumAdicional2 { get; set; }

    public Nullable<decimal> mov_NumAdicional3 { get; set; }

    public string mov_StrAdicional1 { get; set; }

    public string mov_StrAdicional2 { get; set; }

    public string mov_StrAdicional3 { get; set; }



    public virtual ACTIVO ACTIVO { get; set; }

}


public partial class PAIS
{

    public PAIS()
    {

        this.PROVEEDOR = new HashSet<PROVEEDOR>();

        this.PROVEEDOR1 = new HashSet<PROVEEDOR>();

        this.PROVEEDOR2 = new HashSet<PROVEEDOR>();

    }


    public int PAI_ID { get; set; }

    public string PAI_NOMBRE { get; set; }

    public int PAI_NIVEL { get; set; }

    public int PAI_PADRE { get; set; }



    public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }

    public virtual ICollection<PROVEEDOR> PROVEEDOR1 { get; set; }

    public virtual ICollection<PROVEEDOR> PROVEEDOR2 { get; set; }

}


public partial class PARAMETROS
{

    public int par_id { get; set; }

    public string par_nombre { get; set; }

    public string par_valor { get; set; }

    public string par_codigo { get; set; }

}


public partial class POTENCIA_ANTENA
{

    public int potenciaID { get; set; }

    public Nullable<int> potencia { get; set; }

    public Nullable<int> antena { get; set; }

    public string reader { get; set; }

    public string estado { get; set; }

    public Nullable<int> sensibilidad { get; set; }

}


public partial class PPC
{

    public int PPC_NUMERO { get; set; }

    public string PPC_SERIAL { get; set; }

}


public partial class PROVEEDOR
{

    public PROVEEDOR()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

    }


    public int PRO_ID { get; set; }

    public string PRO_RAZON { get; set; }

    public string PRO_NOMBRE { get; set; }

    public string PRO_RUC { get; set; }

    public string PRO_CONTACTO { get; set; }

    public string PRO_DIRECCION { get; set; }

    public string PRO_TELEFONOF { get; set; }

    public string PRO_CELULAR { get; set; }

    public string PRO_FAX { get; set; }

    public string PRO_EMAIL { get; set; }

    public int PRO_CREDITO { get; set; }

    public string PRO_OBSERVACIONES { get; set; }

    public System.DateTime PRO_FECHAREGISTRO { get; set; }

    public int GRU_ID { get; set; }

    public int PAI_ID1 { get; set; }

    public Nullable<int> PAI_ID2 { get; set; }

    public Nullable<int> PAI_ID3 { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

    public virtual GRUPO GRUPO { get; set; }

    public virtual PAIS PAIS { get; set; }

    public virtual PAIS PAIS1 { get; set; }

    public virtual PAIS PAIS2 { get; set; }

}


public partial class REPORTE
{

    public int REP_CODIGO { get; set; }

    public string REP_CODBARRAS { get; set; }

    public Nullable<int> CUS_ID { get; set; }

    public Nullable<System.DateTime> REP_FECHA { get; set; }

    public string REP_ESTADO { get; set; }

    public Nullable<int> ACT_ID { get; set; }

    public string REP_USUARIO { get; set; }

}


public partial class ROLPPC
{

    public ROLPPC()
    {

        this.USUPPC = new HashSet<USUPPC>();

    }


    public int RPP_ID { get; set; }

    public string RPP_NOMBRE { get; set; }



    public virtual ICollection<USUPPC> USUPPC { get; set; }

}


public partial class TIPO_SEGURO
{

    public TIPO_SEGURO()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

    }


    public int SEG_ID { get; set; }

    public string SEG_NOMBRE { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

}


public partial class TIPOMAN
{

    public int TIP_ID { get; set; }

    public string TIP_NOMBRE { get; set; }

}


public partial class UGEOGRAFICA
{

    public UGEOGRAFICA()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

        this.ACTIVO1 = new HashSet<ACTIVO>();

        this.ACTIVO2 = new HashSet<ACTIVO>();

        this.ACTIVO3 = new HashSet<ACTIVO>();

        this.UORGANICA = new HashSet<UORGANICA>();

    }


    public int UGE_ID { get; set; }

    public string UGE_NOMBRE { get; set; }

    public int UGE_PADRE { get; set; }

    public int UGE_NIVEL { get; set; }

    public string UGE_READERIP { get; set; }

    public string UGE_READERNOMBRE { get; set; }

    public string UGE_TIPOREADER { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

    public virtual ICollection<ACTIVO> ACTIVO1 { get; set; }

    public virtual ICollection<ACTIVO> ACTIVO2 { get; set; }

    public virtual ICollection<ACTIVO> ACTIVO3 { get; set; }

    public virtual ICollection<UORGANICA> UORGANICA { get; set; }

}


public partial class UNIDAD
{

    public UNIDAD()
    {

        this.CARACTERISTICA = new HashSet<CARACTERISTICA>();

    }


    public int UNI_ID { get; set; }

    public string UNI_SIMBOLO { get; set; }



    public virtual ICollection<CARACTERISTICA> CARACTERISTICA { get; set; }

}


public partial class UORGANICA
{

    public UORGANICA()
    {

        this.ACTIVO = new HashSet<ACTIVO>();

        this.ACTIVO1 = new HashSet<ACTIVO>();

        this.XCUOR = new HashSet<XCUOR>();

    }


    public int UOR_ID { get; set; }

    public string UOR_NOMBRE { get; set; }

    public int UOR_PADRE { get; set; }

    public int UOR_NIVEL { get; set; }

    public Nullable<int> UGE_ID { get; set; }

    public string UOR_CODIGO { get; set; }

    public string UOR_READERIP { get; set; }

    public string UOR_READERNOMBRE { get; set; }



    public virtual ICollection<ACTIVO> ACTIVO { get; set; }

    public virtual ICollection<ACTIVO> ACTIVO1 { get; set; }

    public virtual UGEOGRAFICA UGEOGRAFICA { get; set; }

    public virtual ICollection<XCUOR> XCUOR { get; set; }

}


public partial class USUPPC
{

    public USUPPC()
    {

        this.ROLPPC = new HashSet<ROLPPC>();

    }


    public string UPP_USUARIO { get; set; }

    public string UPP_CLAVE { get; set; }



    public virtual ICollection<ROLPPC> ROLPPC { get; set; }

}


public partial class Vista_Activos
{

    public int ACT_ID { get; set; }

    public string ACT_CODBARRAS { get; set; }

    public string ACT_CODBARRASPADRE { get; set; }

    public string ACT_CODIGO1 { get; set; }

    public string UGE_NOMBRE1 { get; set; }

    public string UGE_NOMBRE2 { get; set; }

    public string UGE_NOMBRE3 { get; set; }

    public string UGE_NOMBRE4 { get; set; }

    public string UOR_NOMBRE1 { get; set; }

    public string UOR_NOMBRE2 { get; set; }

    public string UOR_NOMBRE3 { get; set; }

    public string CUS_NOMBRE { get; set; }

    public string GRU_NOMBRE1 { get; set; }

    public string GRU_NOMBRE2 { get; set; }

    public string GRU_NOMBRE3 { get; set; }

    public string EST_NOMBRE { get; set; }

    public string MAR_NOMBRE { get; set; }

    public string MOD_NOMBRE { get; set; }

    public string COL_NOMBRE { get; set; }

    public string ECO_NOMBRE1 { get; set; }

    public string ECO_NOMBRE2 { get; set; }

}


public partial class vw_aspnet_Applications
{

    public string ApplicationName { get; set; }

    public string LoweredApplicationName { get; set; }

    public System.Guid ApplicationId { get; set; }

    public string Description { get; set; }

}


public partial class vw_aspnet_MembershipUsers
{

    public System.Guid UserId { get; set; }

    public int PasswordFormat { get; set; }

    public string MobilePIN { get; set; }

    public string Email { get; set; }

    public string LoweredEmail { get; set; }

    public string PasswordQuestion { get; set; }

    public string PasswordAnswer { get; set; }

    public bool IsApproved { get; set; }

    public bool IsLockedOut { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime LastLoginDate { get; set; }

    public System.DateTime LastPasswordChangedDate { get; set; }

    public System.DateTime LastLockoutDate { get; set; }

    public int FailedPasswordAttemptCount { get; set; }

    public System.DateTime FailedPasswordAttemptWindowStart { get; set; }

    public int FailedPasswordAnswerAttemptCount { get; set; }

    public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }

    public string Comment { get; set; }

    public System.Guid ApplicationId { get; set; }

    public string UserName { get; set; }

    public string MobileAlias { get; set; }

    public bool IsAnonymous { get; set; }

    public System.DateTime LastActivityDate { get; set; }

}


public partial class vw_aspnet_Profiles
{

    public System.Guid UserId { get; set; }

    public System.DateTime LastUpdatedDate { get; set; }

    public Nullable<int> DataSize { get; set; }

}


public partial class vw_aspnet_Roles
{

    public System.Guid ApplicationId { get; set; }

    public System.Guid RoleId { get; set; }

    public string RoleName { get; set; }

    public string LoweredRoleName { get; set; }

    public string Description { get; set; }

}


public partial class vw_aspnet_Users
{

    public System.Guid ApplicationId { get; set; }

    public System.Guid UserId { get; set; }

    public string UserName { get; set; }

    public string LoweredUserName { get; set; }

    public string MobileAlias { get; set; }

    public bool IsAnonymous { get; set; }

    public System.DateTime LastActivityDate { get; set; }

}


public partial class vw_aspnet_UsersInRoles
{

    public System.Guid UserId { get; set; }

    public System.Guid RoleId { get; set; }

}


public partial class vw_aspnet_WebPartState_Paths
{

    public System.Guid ApplicationId { get; set; }

    public System.Guid PathId { get; set; }

    public string Path { get; set; }

    public string LoweredPath { get; set; }

}


public partial class vw_aspnet_WebPartState_Shared
{

    public System.Guid PathId { get; set; }

    public Nullable<int> DataSize { get; set; }

    public System.DateTime LastUpdatedDate { get; set; }

}


public partial class vw_aspnet_WebPartState_User
{

    public Nullable<System.Guid> PathId { get; set; }

    public Nullable<System.Guid> UserId { get; set; }

    public Nullable<int> DataSize { get; set; }

    public System.DateTime LastUpdatedDate { get; set; }

}


public partial class XCUOR
{

    public int XCU_ID { get; set; }

    public int CUS_ID { get; set; }

    public int UOR_ID { get; set; }



    public virtual CUSTODIO CUSTODIO { get; set; }

    public virtual UORGANICA UORGANICA { get; set; }

}


public partial class ACTIVOPC01_Result
{

    public int par_id { get; set; }

    public string par_valor { get; set; }

}


public partial class ACTIVOPC02_Result
{

    public int ID { get; set; }

    public string Tipo_Activo { get; set; }

    public string Código { get; set; }

    public Nullable<decimal> Valor_Compra { get; set; }

    public Nullable<decimal> Nº_Factura { get; set; }

    public Nullable<int> Vida_Útil { get; set; }

    public string Código_Padre { get; set; }

    public string Código_1 { get; set; }

    public string Ubi__Geo_1 { get; set; }

    public string Ubi__Geo_2 { get; set; }

    public string Ubi__Geo_3 { get; set; }

    public string Ubi__Geo_4 { get; set; }

    public string Centro_de_Costo { get; set; }

    public string Ubi__Org1 { get; set; }

    public string Ubi__Org2 { get; set; }

    public string Custodio { get; set; }

    public string Grupo { get; set; }

    public string Subgrupo { get; set; }

    public string Descripción { get; set; }

    public string Estado { get; set; }

    public string Observaciones { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public string Nº_Serie { get; set; }

    public Nullable<int> Año { get; set; }

    public string Color { get; set; }

    public string Estructura { get; set; }

    public string Componente { get; set; }

    public string Proveedor { get; set; }

}


public partial class aspnet_Membership_GetPassword_Result
{

    public string Column1 { get; set; }

    public Nullable<int> Column2 { get; set; }

}


public partial class aspnet_Membership_GetPasswordWithFormat_Result
{

    public string Column1 { get; set; }

    public Nullable<int> Column2 { get; set; }

    public string Column3 { get; set; }

    public Nullable<int> Column4 { get; set; }

    public Nullable<int> Column5 { get; set; }

    public Nullable<bool> Column6 { get; set; }

    public Nullable<System.DateTime> Column7 { get; set; }

    public Nullable<System.DateTime> Column8 { get; set; }

}


public partial class aspnet_Membership_GetUserByName_Result
{

    public string Email { get; set; }

    public string PasswordQuestion { get; set; }

    public string Comment { get; set; }

    public bool IsApproved { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime LastLoginDate { get; set; }

    public System.DateTime LastActivityDate { get; set; }

    public System.DateTime LastPasswordChangedDate { get; set; }

    public System.Guid UserId { get; set; }

    public bool IsLockedOut { get; set; }

    public System.DateTime LastLockoutDate { get; set; }

}


public partial class aspnet_Membership_GetUserByUserId_Result
{

    public string Email { get; set; }

    public string PasswordQuestion { get; set; }

    public string Comment { get; set; }

    public bool IsApproved { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime LastLoginDate { get; set; }

    public System.DateTime LastActivityDate { get; set; }

    public System.DateTime LastPasswordChangedDate { get; set; }

    public string UserName { get; set; }

    public bool IsLockedOut { get; set; }

    public System.DateTime LastLockoutDate { get; set; }

}


public partial class aspnet_Profile_GetProperties_Result
{

    public string PropertyNames { get; set; }

    public string PropertyValuesString { get; set; }

    public byte[] PropertyValuesBinary { get; set; }

}


public partial class aspnet_UsersInRoles_RemoveUsersFromRoles_Result
{

    public string Column1 { get; set; }

    public string Name { get; set; }

}


public partial class LECTURA_MOVIMIENTOSPC01_Result
{

    public int ID { get; set; }

    public string Codigo_de_Barras { get; set; }

    public string Codigo_Secundario { get; set; }

    public string Grupo { get; set; }

    public string Nombre_Bien { get; set; }

    public string Tipo { get; set; }

    public string custodio { get; set; }

    public string Estado { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public string Hora { get; set; }

    public string Portal { get; set; }

    public Nullable<int> Antena { get; set; }

}


public partial class PARAMETROSPC01_Result
{

    public int par_id { get; set; }

    public string par_valor { get; set; }

}


public partial class REPORTEMOVILPC01_Result
{

    public string Código_Barras { get; set; }

    public string Código_Secundario { get; set; }

    public string Tipo { get; set; }

    public string Descripción { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public string Serie { get; set; }

    public string Custodio { get; set; }

    public string Estado { get; set; }

}


public partial class usp_getActivomantenimiento_Result
{

    public string CODIGO { get; set; }

    public int ID { get; set; }

    public string GRUPO { get; set; }

    public Nullable<int> SUBGRUPO { get; set; }

    public Nullable<int> DESCRIPCION { get; set; }

    public string UG1 { get; set; }

    public Nullable<int> UG2 { get; set; }

    public Nullable<int> UG3 { get; set; }

    public string UO1 { get; set; }

    public Nullable<int> UO2 { get; set; }

    public Nullable<int> UO3 { get; set; }

}


public partial class usp_getDatosPdf_Result
{

    public string CODIGO { get; set; }

    public string CÓDIGO_LOGIKARD { get; set; }

    public string SUBTIPO { get; set; }

    public string CLASE { get; set; }

    public string DESCRIPCION { get; set; }

    public string DETALLE { get; set; }

    public string ESTADO { get; set; }

    public string MARCA { get; set; }

    public string act_serie1 { get; set; }

    public string MODELO { get; set; }

    public string OBSERVACIONES { get; set; }

}


public partial class usp_getDatosPdf2_Result
{

    public string CODIGO { get; set; }

    public string SUBTIPO { get; set; }

    public string CLASE { get; set; }

    public string ESTADO { get; set; }

    public string UbGeografica { get; set; }

    public string UbOrganica { get; set; }

    public string cus_nombres { get; set; }

    public string Custodio { get; set; }

}


public partial class usp_getFiltroActivoPpc_Result
{

    public Nullable<int> PocketPC { get; set; }

    public string Tipo { get; set; }

    public int Id { get; set; }

    public string Codigo_Barras { get; set; }

    public string Dirección { get; set; }

    public string Ubi__Organica_2 { get; set; }

    public string Ubi__Organica_3 { get; set; }

    public string Custodio { get; set; }

    public string Grupo_Cuenta { get; set; }

    public string Subgrupo { get; set; }

    public string Descripcion { get; set; }

}


public partial class usp_GetReporteGlobalAval_Result
{

    public int ID { get; set; }

    public string FECHA_DE_INGRESO { get; set; }

    public string DIGITADOR { get; set; }

    public string FECHA_DE_INVENTARIO { get; set; }

    public string PERITO { get; set; }

    public string HOJA { get; set; }

    public string TIPO_ACTIVO { get; set; }

    public string UBICACION_GEOGRAFICA_1 { get; set; }

    public string UBICACION_GEOGRAFICA_2 { get; set; }

    public string UBICACION_GEOGRAFICA_3 { get; set; }

    public string PISO { get; set; }

    public string CENTRO_DE_COSTO { get; set; }

    public string UBICACION_ORGANICA_1 { get; set; }

    public string UBICACION_ORGANICA_2 { get; set; }

    public string CUSTODIO { get; set; }

    public string RESPONSABLE { get; set; }

    public string CODIGO_DE_BARRAS { get; set; }

    public string CODIGO_DE_BARRAS_PADRE { get; set; }

    public string GRUPO { get; set; }

    public string SUBGRUPO { get; set; }

    public string DESCRIPCION { get; set; }

    public string CODIGO_1 { get; set; }

    public string ESTADO_1 { get; set; }

    public string ESTADO_2 { get; set; }

    public string ESTADO_3 { get; set; }

    public string FOTO { get; set; }

    public string ACT_FOTO2 { get; set; }

    public string ACT_DOC1 { get; set; }

    public string ACT_DOC2 { get; set; }

    public string DESCRIPCION_LARGA { get; set; }

    public string OBSERVACIONES_AVALUAC { get; set; }

    public string OBSERVACIONES { get; set; }

    public string MARCA { get; set; }

    public string MODELO { get; set; }

    public string SERIE { get; set; }

    public Nullable<int> AÑO { get; set; }

    public string COLOR { get; set; }

    public string ESTRUCTURA { get; set; }

    public string COMPONENTE { get; set; }

}


public partial class usp_getReporteMantenimiento_Result
{

    public System.DateTime Fecha { get; set; }

    public string Técnico { get; set; }

    public string Tipo { get; set; }

    public string Descripción { get; set; }

}


public partial class usp_getReporteTransfer_Result
{

    public string Usuario { get; set; }

    public System.DateTime Fecha { get; set; }

    public string Ub__Geo__1 { get; set; }

    public string Ub__Geo__2 { get; set; }

    public string Ub__Geo__3 { get; set; }

    public string Centro_de_Costo { get; set; }

    public string Ub__Org__2 { get; set; }

    public string Ub__Org__3 { get; set; }

    public string Custodio { get; set; }

    public string Estado { get; set; }

    public string Fase { get; set; }

    public string Transferencia { get; set; }

}


public partial class usp_getUgeAll3Level1_Result
{

    public string uge_NOMBRE { get; set; }

    public int uge_ID { get; set; }

}


public partial class usp_getUgeAll3Level2_Result
{

    public string uge_NOMBRE { get; set; }

    public int uge_ID { get; set; }

}


public partial class usp_getUgeAll3Level3_Result
{

    public string uge_NOMBRE { get; set; }

    public int uge_ID { get; set; }

}


public partial class usp_SummaryLoginS_Result
{

    public Nullable<int> Ultimas24H { get; set; }

    public Nullable<int> UltimaSemana { get; set; }

    public Nullable<int> UltimoMes { get; set; }

    public Nullable<int> Total { get; set; }

}

